// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nmea.proto

package dataguru.codec.zeromq;

public final class NmeaMessage {
  private NmeaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParameterNmeaMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ParameterNmeaMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required double time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required double time = 2;</code>
     */
    double getTime();

    /**
     * <code>required double latitude = 3;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 3;</code>
     */
    double getLatitude();

    /**
     * <code>required double longitude = 4;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 4;</code>
     */
    double getLongitude();

    /**
     * <code>required uint32 fixed = 5;</code>
     */
    boolean hasFixed();
    /**
     * <code>required uint32 fixed = 5;</code>
     */
    int getFixed();

    /**
     * <code>required uint32 quality = 6;</code>
     */
    boolean hasQuality();
    /**
     * <code>required uint32 quality = 6;</code>
     */
    int getQuality();

    /**
     * <code>required double dir = 7;</code>
     */
    boolean hasDir();
    /**
     * <code>required double dir = 7;</code>
     */
    double getDir();

    /**
     * <code>required double altitude = 8;</code>
     */
    boolean hasAltitude();
    /**
     * <code>required double altitude = 8;</code>
     */
    double getAltitude();

    /**
     * <code>required double velocity = 9;</code>
     */
    boolean hasVelocity();
    /**
     * <code>required double velocity = 9;</code>
     */
    double getVelocity();
  }
  /**
   * Protobuf type {@code ParameterNmeaMessage}
   */
  public static final class ParameterNmeaMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ParameterNmeaMessage)
      ParameterNmeaMessageOrBuilder {
    // Use ParameterNmeaMessage.newBuilder() to construct.
    private ParameterNmeaMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ParameterNmeaMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ParameterNmeaMessage defaultInstance;
    public static ParameterNmeaMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ParameterNmeaMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ParameterNmeaMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              time_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              latitude_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              longitude_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              fixed_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              quality_ = input.readUInt32();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              dir_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              altitude_ = input.readDouble();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              velocity_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dataguru.codec.zeromq.NmeaMessage.internal_static_ParameterNmeaMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dataguru.codec.zeromq.NmeaMessage.internal_static_ParameterNmeaMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage.class, dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ParameterNmeaMessage> PARSER =
        new com.google.protobuf.AbstractParser<ParameterNmeaMessage>() {
      public ParameterNmeaMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParameterNmeaMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ParameterNmeaMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private double time_;
    /**
     * <code>required double time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double time = 2;</code>
     */
    public double getTime() {
      return time_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_;
    /**
     * <code>required double latitude = 3;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double latitude = 3;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_;
    /**
     * <code>required double longitude = 4;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double longitude = 4;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int FIXED_FIELD_NUMBER = 5;
    private int fixed_;
    /**
     * <code>required uint32 fixed = 5;</code>
     */
    public boolean hasFixed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 fixed = 5;</code>
     */
    public int getFixed() {
      return fixed_;
    }

    public static final int QUALITY_FIELD_NUMBER = 6;
    private int quality_;
    /**
     * <code>required uint32 quality = 6;</code>
     */
    public boolean hasQuality() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint32 quality = 6;</code>
     */
    public int getQuality() {
      return quality_;
    }

    public static final int DIR_FIELD_NUMBER = 7;
    private double dir_;
    /**
     * <code>required double dir = 7;</code>
     */
    public boolean hasDir() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required double dir = 7;</code>
     */
    public double getDir() {
      return dir_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 8;
    private double altitude_;
    /**
     * <code>required double altitude = 8;</code>
     */
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required double altitude = 8;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    public static final int VELOCITY_FIELD_NUMBER = 9;
    private double velocity_;
    /**
     * <code>required double velocity = 9;</code>
     */
    public boolean hasVelocity() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required double velocity = 9;</code>
     */
    public double getVelocity() {
      return velocity_;
    }

    private void initFields() {
      type_ = "";
      time_ = 0D;
      latitude_ = 0D;
      longitude_ = 0D;
      fixed_ = 0;
      quality_ = 0;
      dir_ = 0D;
      altitude_ = 0D;
      velocity_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFixed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuality()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAltitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVelocity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, fixed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, quality_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, dir_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, altitude_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, velocity_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, fixed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, quality_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, dir_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, altitude_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, velocity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ParameterNmeaMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ParameterNmeaMessage)
        dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dataguru.codec.zeromq.NmeaMessage.internal_static_ParameterNmeaMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dataguru.codec.zeromq.NmeaMessage.internal_static_ParameterNmeaMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage.class, dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage.Builder.class);
      }

      // Construct using dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        fixed_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        quality_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        dir_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        altitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        velocity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dataguru.codec.zeromq.NmeaMessage.internal_static_ParameterNmeaMessage_descriptor;
      }

      public dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage getDefaultInstanceForType() {
        return dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage.getDefaultInstance();
      }

      public dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage build() {
        dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage buildPartial() {
        dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage result = new dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fixed_ = fixed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.quality_ = quality_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.dir_ = dir_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.altitude_ = altitude_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.velocity_ = velocity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage) {
          return mergeFrom((dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage other) {
        if (other == dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasFixed()) {
          setFixed(other.getFixed());
        }
        if (other.hasQuality()) {
          setQuality(other.getQuality());
        }
        if (other.hasDir()) {
          setDir(other.getDir());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasVelocity()) {
          setVelocity(other.getVelocity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasFixed()) {
          
          return false;
        }
        if (!hasQuality()) {
          
          return false;
        }
        if (!hasDir()) {
          
          return false;
        }
        if (!hasAltitude()) {
          
          return false;
        }
        if (!hasVelocity()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dataguru.codec.zeromq.NmeaMessage.ParameterNmeaMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>required double time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double time = 2;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>required double time = 2;</code>
       */
      public Builder setTime(double value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>required double latitude = 3;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double latitude = 3;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 3;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000004;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 3;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 4;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double longitude = 4;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 4;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000008;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 4;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private int fixed_ ;
      /**
       * <code>required uint32 fixed = 5;</code>
       */
      public boolean hasFixed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 fixed = 5;</code>
       */
      public int getFixed() {
        return fixed_;
      }
      /**
       * <code>required uint32 fixed = 5;</code>
       */
      public Builder setFixed(int value) {
        bitField0_ |= 0x00000010;
        fixed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 fixed = 5;</code>
       */
      public Builder clearFixed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fixed_ = 0;
        onChanged();
        return this;
      }

      private int quality_ ;
      /**
       * <code>required uint32 quality = 6;</code>
       */
      public boolean hasQuality() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint32 quality = 6;</code>
       */
      public int getQuality() {
        return quality_;
      }
      /**
       * <code>required uint32 quality = 6;</code>
       */
      public Builder setQuality(int value) {
        bitField0_ |= 0x00000020;
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 quality = 6;</code>
       */
      public Builder clearQuality() {
        bitField0_ = (bitField0_ & ~0x00000020);
        quality_ = 0;
        onChanged();
        return this;
      }

      private double dir_ ;
      /**
       * <code>required double dir = 7;</code>
       */
      public boolean hasDir() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required double dir = 7;</code>
       */
      public double getDir() {
        return dir_;
      }
      /**
       * <code>required double dir = 7;</code>
       */
      public Builder setDir(double value) {
        bitField0_ |= 0x00000040;
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double dir = 7;</code>
       */
      public Builder clearDir() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dir_ = 0D;
        onChanged();
        return this;
      }

      private double altitude_ ;
      /**
       * <code>required double altitude = 8;</code>
       */
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required double altitude = 8;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>required double altitude = 8;</code>
       */
      public Builder setAltitude(double value) {
        bitField0_ |= 0x00000080;
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double altitude = 8;</code>
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000080);
        altitude_ = 0D;
        onChanged();
        return this;
      }

      private double velocity_ ;
      /**
       * <code>required double velocity = 9;</code>
       */
      public boolean hasVelocity() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required double velocity = 9;</code>
       */
      public double getVelocity() {
        return velocity_;
      }
      /**
       * <code>required double velocity = 9;</code>
       */
      public Builder setVelocity(double value) {
        bitField0_ |= 0x00000100;
        velocity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double velocity = 9;</code>
       */
      public Builder clearVelocity() {
        bitField0_ = (bitField0_ & ~0x00000100);
        velocity_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ParameterNmeaMessage)
    }

    static {
      defaultInstance = new ParameterNmeaMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ParameterNmeaMessage)
  }

  public interface VDMNmeaMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VDMNmeaMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required uint32 numMsgParts = 2;</code>
     */
    boolean hasNumMsgParts();
    /**
     * <code>required uint32 numMsgParts = 2;</code>
     */
    int getNumMsgParts();

    /**
     * <code>required uint32 msgPartNum = 3;</code>
     */
    boolean hasMsgPartNum();
    /**
     * <code>required uint32 msgPartNum = 3;</code>
     */
    int getMsgPartNum();

    /**
     * <code>required uint32 seqMsgID = 4;</code>
     */
    boolean hasSeqMsgID();
    /**
     * <code>required uint32 seqMsgID = 4;</code>
     */
    int getSeqMsgID();

    /**
     * <code>required string channel = 5;</code>
     */
    boolean hasChannel();
    /**
     * <code>required string channel = 5;</code>
     */
    java.lang.String getChannel();
    /**
     * <code>required string channel = 5;</code>
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>required string msgData = 6;</code>
     */
    boolean hasMsgData();
    /**
     * <code>required string msgData = 6;</code>
     */
    java.lang.String getMsgData();
    /**
     * <code>required string msgData = 6;</code>
     */
    com.google.protobuf.ByteString
        getMsgDataBytes();

    /**
     * <code>required string msgBinary = 7;</code>
     */
    boolean hasMsgBinary();
    /**
     * <code>required string msgBinary = 7;</code>
     */
    java.lang.String getMsgBinary();
    /**
     * <code>required string msgBinary = 7;</code>
     */
    com.google.protobuf.ByteString
        getMsgBinaryBytes();

    /**
     * <code>required string checksum = 8;</code>
     */
    boolean hasChecksum();
    /**
     * <code>required string checksum = 8;</code>
     */
    java.lang.String getChecksum();
    /**
     * <code>required string checksum = 8;</code>
     */
    com.google.protobuf.ByteString
        getChecksumBytes();

    /**
     * <code>required uint32 msgType = 9;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required uint32 msgType = 9;</code>
     */
    int getMsgType();
  }
  /**
   * Protobuf type {@code VDMNmeaMessage}
   */
  public static final class VDMNmeaMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VDMNmeaMessage)
      VDMNmeaMessageOrBuilder {
    // Use VDMNmeaMessage.newBuilder() to construct.
    private VDMNmeaMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VDMNmeaMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VDMNmeaMessage defaultInstance;
    public static VDMNmeaMessage getDefaultInstance() {
      return defaultInstance;
    }

    public VDMNmeaMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VDMNmeaMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              numMsgParts_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgPartNum_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              seqMsgID_ = input.readUInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              channel_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              msgData_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              msgBinary_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              checksum_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              msgType_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dataguru.codec.zeromq.NmeaMessage.internal_static_VDMNmeaMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dataguru.codec.zeromq.NmeaMessage.internal_static_VDMNmeaMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage.class, dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<VDMNmeaMessage> PARSER =
        new com.google.protobuf.AbstractParser<VDMNmeaMessage>() {
      public VDMNmeaMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VDMNmeaMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VDMNmeaMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMMSGPARTS_FIELD_NUMBER = 2;
    private int numMsgParts_;
    /**
     * <code>required uint32 numMsgParts = 2;</code>
     */
    public boolean hasNumMsgParts() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 numMsgParts = 2;</code>
     */
    public int getNumMsgParts() {
      return numMsgParts_;
    }

    public static final int MSGPARTNUM_FIELD_NUMBER = 3;
    private int msgPartNum_;
    /**
     * <code>required uint32 msgPartNum = 3;</code>
     */
    public boolean hasMsgPartNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 msgPartNum = 3;</code>
     */
    public int getMsgPartNum() {
      return msgPartNum_;
    }

    public static final int SEQMSGID_FIELD_NUMBER = 4;
    private int seqMsgID_;
    /**
     * <code>required uint32 seqMsgID = 4;</code>
     */
    public boolean hasSeqMsgID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 seqMsgID = 4;</code>
     */
    public int getSeqMsgID() {
      return seqMsgID_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 5;
    private java.lang.Object channel_;
    /**
     * <code>required string channel = 5;</code>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string channel = 5;</code>
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string channel = 5;</code>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGDATA_FIELD_NUMBER = 6;
    private java.lang.Object msgData_;
    /**
     * <code>required string msgData = 6;</code>
     */
    public boolean hasMsgData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string msgData = 6;</code>
     */
    public java.lang.String getMsgData() {
      java.lang.Object ref = msgData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgData = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMsgDataBytes() {
      java.lang.Object ref = msgData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGBINARY_FIELD_NUMBER = 7;
    private java.lang.Object msgBinary_;
    /**
     * <code>required string msgBinary = 7;</code>
     */
    public boolean hasMsgBinary() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string msgBinary = 7;</code>
     */
    public java.lang.String getMsgBinary() {
      java.lang.Object ref = msgBinary_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgBinary_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgBinary = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBinaryBytes() {
      java.lang.Object ref = msgBinary_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgBinary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKSUM_FIELD_NUMBER = 8;
    private java.lang.Object checksum_;
    /**
     * <code>required string checksum = 8;</code>
     */
    public boolean hasChecksum() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string checksum = 8;</code>
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          checksum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string checksum = 8;</code>
     */
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 9;
    private int msgType_;
    /**
     * <code>required uint32 msgType = 9;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required uint32 msgType = 9;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    private void initFields() {
      type_ = "";
      numMsgParts_ = 0;
      msgPartNum_ = 0;
      seqMsgID_ = 0;
      channel_ = "";
      msgData_ = "";
      msgBinary_ = "";
      checksum_ = "";
      msgType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumMsgParts()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgPartNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeqMsgID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgBinary()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChecksum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, numMsgParts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, msgPartNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, seqMsgID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getChannelBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getMsgDataBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getMsgBinaryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getChecksumBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, msgType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, numMsgParts_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, msgPartNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, seqMsgID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getChannelBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMsgDataBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMsgBinaryBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getChecksumBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, msgType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VDMNmeaMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VDMNmeaMessage)
        dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dataguru.codec.zeromq.NmeaMessage.internal_static_VDMNmeaMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dataguru.codec.zeromq.NmeaMessage.internal_static_VDMNmeaMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage.class, dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage.Builder.class);
      }

      // Construct using dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        numMsgParts_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgPartNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        seqMsgID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        channel_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        msgData_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        msgBinary_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        checksum_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dataguru.codec.zeromq.NmeaMessage.internal_static_VDMNmeaMessage_descriptor;
      }

      public dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage getDefaultInstanceForType() {
        return dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage.getDefaultInstance();
      }

      public dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage build() {
        dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage buildPartial() {
        dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage result = new dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.numMsgParts_ = numMsgParts_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgPartNum_ = msgPartNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.seqMsgID_ = seqMsgID_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgData_ = msgData_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgBinary_ = msgBinary_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.checksum_ = checksum_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.msgType_ = msgType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage) {
          return mergeFrom((dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage other) {
        if (other == dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasNumMsgParts()) {
          setNumMsgParts(other.getNumMsgParts());
        }
        if (other.hasMsgPartNum()) {
          setMsgPartNum(other.getMsgPartNum());
        }
        if (other.hasSeqMsgID()) {
          setSeqMsgID(other.getSeqMsgID());
        }
        if (other.hasChannel()) {
          bitField0_ |= 0x00000010;
          channel_ = other.channel_;
          onChanged();
        }
        if (other.hasMsgData()) {
          bitField0_ |= 0x00000020;
          msgData_ = other.msgData_;
          onChanged();
        }
        if (other.hasMsgBinary()) {
          bitField0_ |= 0x00000040;
          msgBinary_ = other.msgBinary_;
          onChanged();
        }
        if (other.hasChecksum()) {
          bitField0_ |= 0x00000080;
          checksum_ = other.checksum_;
          onChanged();
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasNumMsgParts()) {
          
          return false;
        }
        if (!hasMsgPartNum()) {
          
          return false;
        }
        if (!hasSeqMsgID()) {
          
          return false;
        }
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasMsgData()) {
          
          return false;
        }
        if (!hasMsgBinary()) {
          
          return false;
        }
        if (!hasChecksum()) {
          
          return false;
        }
        if (!hasMsgType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dataguru.codec.zeromq.NmeaMessage.VDMNmeaMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private int numMsgParts_ ;
      /**
       * <code>required uint32 numMsgParts = 2;</code>
       */
      public boolean hasNumMsgParts() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 numMsgParts = 2;</code>
       */
      public int getNumMsgParts() {
        return numMsgParts_;
      }
      /**
       * <code>required uint32 numMsgParts = 2;</code>
       */
      public Builder setNumMsgParts(int value) {
        bitField0_ |= 0x00000002;
        numMsgParts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 numMsgParts = 2;</code>
       */
      public Builder clearNumMsgParts() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numMsgParts_ = 0;
        onChanged();
        return this;
      }

      private int msgPartNum_ ;
      /**
       * <code>required uint32 msgPartNum = 3;</code>
       */
      public boolean hasMsgPartNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 msgPartNum = 3;</code>
       */
      public int getMsgPartNum() {
        return msgPartNum_;
      }
      /**
       * <code>required uint32 msgPartNum = 3;</code>
       */
      public Builder setMsgPartNum(int value) {
        bitField0_ |= 0x00000004;
        msgPartNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 msgPartNum = 3;</code>
       */
      public Builder clearMsgPartNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgPartNum_ = 0;
        onChanged();
        return this;
      }

      private int seqMsgID_ ;
      /**
       * <code>required uint32 seqMsgID = 4;</code>
       */
      public boolean hasSeqMsgID() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 seqMsgID = 4;</code>
       */
      public int getSeqMsgID() {
        return seqMsgID_;
      }
      /**
       * <code>required uint32 seqMsgID = 4;</code>
       */
      public Builder setSeqMsgID(int value) {
        bitField0_ |= 0x00000008;
        seqMsgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 seqMsgID = 4;</code>
       */
      public Builder clearSeqMsgID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        seqMsgID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object channel_ = "";
      /**
       * <code>required string channel = 5;</code>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string channel = 5;</code>
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string channel = 5;</code>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string channel = 5;</code>
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string channel = 5;</code>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>required string channel = 5;</code>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        channel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgData_ = "";
      /**
       * <code>required string msgData = 6;</code>
       */
      public boolean hasMsgData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string msgData = 6;</code>
       */
      public java.lang.String getMsgData() {
        java.lang.Object ref = msgData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgData = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMsgDataBytes() {
        java.lang.Object ref = msgData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgData = 6;</code>
       */
      public Builder setMsgData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgData = 6;</code>
       */
      public Builder clearMsgData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgData_ = getDefaultInstance().getMsgData();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgData = 6;</code>
       */
      public Builder setMsgDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        msgData_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgBinary_ = "";
      /**
       * <code>required string msgBinary = 7;</code>
       */
      public boolean hasMsgBinary() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string msgBinary = 7;</code>
       */
      public java.lang.String getMsgBinary() {
        java.lang.Object ref = msgBinary_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgBinary_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgBinary = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBinaryBytes() {
        java.lang.Object ref = msgBinary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgBinary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgBinary = 7;</code>
       */
      public Builder setMsgBinary(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgBinary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgBinary = 7;</code>
       */
      public Builder clearMsgBinary() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgBinary_ = getDefaultInstance().getMsgBinary();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgBinary = 7;</code>
       */
      public Builder setMsgBinaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgBinary_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object checksum_ = "";
      /**
       * <code>required string checksum = 8;</code>
       */
      public boolean hasChecksum() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string checksum = 8;</code>
       */
      public java.lang.String getChecksum() {
        java.lang.Object ref = checksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            checksum_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string checksum = 8;</code>
       */
      public com.google.protobuf.ByteString
          getChecksumBytes() {
        java.lang.Object ref = checksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string checksum = 8;</code>
       */
      public Builder setChecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string checksum = 8;</code>
       */
      public Builder clearChecksum() {
        bitField0_ = (bitField0_ & ~0x00000080);
        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }
      /**
       * <code>required string checksum = 8;</code>
       */
      public Builder setChecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        checksum_ = value;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>required uint32 msgType = 9;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required uint32 msgType = 9;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>required uint32 msgType = 9;</code>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000100;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 msgType = 9;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        msgType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VDMNmeaMessage)
    }

    static {
      defaultInstance = new VDMNmeaMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VDMNmeaMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParameterNmeaMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ParameterNmeaMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VDMNmeaMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VDMNmeaMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnmea.proto\"\250\001\n\024ParameterNmeaMessage\022\014\n" +
      "\004type\030\001 \002(\t\022\014\n\004time\030\002 \002(\001\022\020\n\010latitude\030\003 " +
      "\002(\001\022\021\n\tlongitude\030\004 \002(\001\022\r\n\005fixed\030\005 \002(\r\022\017\n" +
      "\007quality\030\006 \002(\r\022\013\n\003dir\030\007 \002(\001\022\020\n\010altitude\030" +
      "\010 \002(\001\022\020\n\010velocity\030\t \002(\001\"\261\001\n\016VDMNmeaMessa" +
      "ge\022\014\n\004type\030\001 \002(\t\022\023\n\013numMsgParts\030\002 \002(\r\022\022\n" +
      "\nmsgPartNum\030\003 \002(\r\022\020\n\010seqMsgID\030\004 \002(\r\022\017\n\007c" +
      "hannel\030\005 \002(\t\022\017\n\007msgData\030\006 \002(\t\022\021\n\tmsgBina" +
      "ry\030\007 \002(\t\022\020\n\010checksum\030\010 \002(\t\022\017\n\007msgType\030\t " +
      "\002(\rB$\n\025dataguru.codec.zeromqB\013NmeaMessag",
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ParameterNmeaMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ParameterNmeaMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ParameterNmeaMessage_descriptor,
        new java.lang.String[] { "Type", "Time", "Latitude", "Longitude", "Fixed", "Quality", "Dir", "Altitude", "Velocity", });
    internal_static_VDMNmeaMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VDMNmeaMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VDMNmeaMessage_descriptor,
        new java.lang.String[] { "Type", "NumMsgParts", "MsgPartNum", "SeqMsgID", "Channel", "MsgData", "MsgBinary", "Checksum", "MsgType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
